### ISSUE TITLE
No data reported at all by sockdump.py

### ISSUE THREAD

**Issue by sanderjo** [mechpen/sockdump#5] opened 2021-01-06 21:49 UTC
I start like in the README:
```
sander@witte2004:~/git/sockdump$ sudo ./sockdump.py --format string /var/run/docker.sock
waiting for data

```
and then I do a lot of docker interaction (docker ps, docker run ..., access the webinterface in that container), but ... nothing appears on the output sockdump.py

Help appreciated!

**Comment by mechpen** [comment] 2021-01-17 23:52
Hi, I just saw your message.  Could you check if dockerd is listening at `/var/run/docker.sock`?  You could find out by running `sudo netstat -lxp | grep dockerd`

**Comment by piec** [comment] 2021-02-18 13:37
In my case dockerd listens on
```
u_str LISTEN 0      4096                                /run/docker.sock 16960                    * 0                                                  
```

`/var/run` is a symlink to `/run`

I tried both
```
sudo ./sockdump.py --format string /var/run/docker.sock
sudo ./sockdump.py --format string /run/docker.sock
```
but I'm not getting data, kernel 5.4.0 (aws)

**Comment by piec** [comment] 2021-02-18 13:42
I commented out the [filter lines](https://github.com/mechpen/sockdump/blob/f5d20c8d10a2c824827dd071fd286bec60e9d94a/sockdump.py#L59-L60) and it works actually

**Comment by mechpen** [comment] 2021-02-18 16:14
If you comment out the filter lines, then all socket traffic is captured.

Could you help troubleshoot with the following?

1. apply the following patch to print out the actual socket path:
```
diff --git a/sockdump.py b/sockdump.py
index e94248be0e6b..e04ced983d71 100755
--- a/sockdump.py
+++ b/sockdump.py
@@ -51,9 +51,11 @@ int probe_unix_stream_sendmsg(struct pt_regs *ctx,
     addr = ((struct unix_sock *)sock->sk)->addr;
     path = addr->name->sun_path;
     __FILTER__
+    bpf_trace_printk("my path: %s\\n", path);

     addr = ((struct unix_sock *)((struct unix_sock *)sock->sk)->peer)->addr;
     path = addr->name->sun_path;
     __FILTER__
+    bpf_trace_printk("peer path: %s\\n", path);

     if (match == 0)
```
2. get the output of the following command:

    `sudo cat /sys/kernel/debug/tracing/trace_pipe | grep docker.sock`

**Comment by piec** [comment] 2021-02-18 16:19
I did more or less the same :)
I'm getting weird results, but I haven't had the time to investigate yet
```diff
diff --git a/sockdump.py b/sockdump.py
index e94248b..3fcdc22 100755
--- a/sockdump.py
+++ b/sockdump.py
@@ -50,14 +50,18 @@ int probe_unix_stream_sendmsg(struct pt_regs *ctx,

     addr = ((struct unix_sock *)sock->sk)->addr;
     path = addr->name->sun_path;
+    bpf_trace_printk("a=%s\\n", addr->name->sun_path);
+    bpf_trace_printk("a=%s\\n", &addr->name->sun_path[0]);
+    bpf_trace_printk("a=%s\\n", path);
     __FILTER__

     addr = ((struct unix_sock *)((struct unix_sock *)sock->sk)->peer)->addr;
     path = addr->name->sun_path;
+    bpf_trace_printk("b=%s\\n", &addr->name->sun_path);
     __FILTER__

-    if (match == 0)
-        return 0;
+    //if (match == 0)
+        //return 0;

     n = bpf_get_smp_processor_id();
     packet = packet_array.lookup(&n);
```
Some sample results:
```
         dockerd-651   [000] .... 685284.801824: 0: a=|||||||||||
         dockerd-651   [000] .... 685284.801848: 0: a=|a=%s

         dockerd-651   [000] .... 685284.801848: 0: a=a=%s

         dockerd-651   [000] .... 685284.801850: 0: b=$7b=%s

           <...>-57791 [000] .... 685286.745435: 0: a=
           <...>-57791 [000] .N.. 685286.745462: 0: a=
           <...>-57791 [000] .N.. 685286.745463: 0: a=a=%s

           <...>-57791 [000] .N.. 685286.745464: 0: b=$7b=%s

           <...>-57794 [000] .... 685287.805162: 0: a=
           <...>-57794 [000] .N.. 685287.805188: 0: a=
           <...>-57794 [000] .N.. 685287.805189: 0: a=a=%s

           <...>-57794 [000] .N.. 685287.805190: 0: b=$7b=%s
```

**Comment by piec** [comment] 2021-02-18 16:33
I noticed that `sock->sk->addr` can be null, but it doesn't crash when doing `addr->name->sun_path`.

```diff
--- a/sockdump.py
+++ b/sockdump.py
@@ -50,14 +50,20 @@ int probe_unix_stream_sendmsg(struct pt_regs *ctx,

     addr = ((struct unix_sock *)sock->sk)->addr;
     path = addr->name->sun_path;
-    __FILTER__
+    bpf_trace_printk("sock=%p sk=%p addr=%p\\n", sock, sock->sk, ((struct unix_sock *)sock->sk)->addr);
+    if (addr != NULL) {
+        bpf_trace_printk("addr=%p name=%p sun_path%p\\n", addr, addr->name, addr->name->sun_path);
+        bpf_trace_printk("path=%s\\n", path);
+    }
+    //__FILTER__
```
Example output:
```
           <...>-34550 [000] .... 686196.900517: 0: sock=00000000807ec504 sk=00000000df8ae7d7 addr=0000000000000000
           <...>-59190 [000] .... 686197.111763: 0: sock=00000000483c4b0f sk=00000000cc529dfd addr=0000000000000000
         dockerd-651   [000] .... 686197.112664: 0: sock=00000000f0810de6 sk=0000000031cb15c3 addr=000000008c451248
         dockerd-651   [000] .... 686197.112688: 0: addr=000000008c451248 name=00000000ab2de4e5 sun_path0000000085e0d34f
         dockerd-651   [000] .... 686197.112689: 0: path=path=%s
```

**Comment by mechpen** [comment] 2021-02-18 16:45
Interesting.  If you could share the base AWS AMI id.  I could try it out in AWS.

**Comment by piec** [comment] 2021-02-18 16:55
For example: `ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210129`
AMI ID: `ami-0932440befd74cdba`

**Comment by mechpen** [comment] 2021-02-21 02:53
I reproduced in ubuntu and fixed in 21eb5118104.  Could you verify?

**Comment by mechpen** [comment] 2021-02-21 05:47
A better fix is in 20bb15b37716a7bfc99f9ab1d28ce412b0c20aca.

**Comment by piec** [comment] 2021-02-22 10:34
Thanks it works for me too :+1: 

Can you explain the change in https://github.com/mechpen/sockdump/commit/20bb15b37716a7bfc99f9ab1d28ce412b0c20aca?
You're reading (and copying) the sun_path with `bpf_probe_read` to dectect wrong memory accesses?

**Comment by mechpen** [comment] 2021-02-23 00:24
Bcc translates struct field access to `bpf_probe_read` calls because the bpf virtual machine does not have memory.  For example,  for `sock->sk`, bcc translates to `bpf_probe_read(stack_var, 8, sock+sk_offset)`.

Sometimes bcc cannot translate correctly, so we have to explicitly call `bpf_probe_read`.

The change in 20bb15b37716a7bfc99f9ab1d28ce412b0c20aca also optimize by using one `bpf_probe_read` to copy the full path to bpf stack, instead of calling `bpf_probe_read` for each char.

**Comment by piec** [comment] 2021-02-23 13:32
ok thank you :)

**Closed as completed** 2021-03-04 18:20 UTC
